apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-deploy-hpa
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    #apiVersion: extensions/v1beta1
    apiVersion: apps/v1
    kind: deployment
    name: nginx-deploy
  targetCPUUtilizationPercentage: 5
