apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  ports:
  - nodePort: 31196
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-app

